language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t ezhilraj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ezhilraj/react-test npm test -- --coverage

after_sucess: 
  - docker build -t ezhilraj/multi-client ./client 
  - docker build -t ezhilraj/multi-nginx ./nginx
  - docker build -t ezhilraj/multi-server ./server
  - docker build -t ezhilraj/multi-worker ./worker
  

  #log into docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ezhilraj/multi-client
  - docker push ezhilraj/multi-nginx
  - docker push ezhilraj/multi-server
  - docker push ezhilraj/multi-worker